name: Docker Build and Push
on:
  push:
    tags:
      - "*"

concurrency:
  group: "docker-image"
  cancel-in-progress: false

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to tjjs
      uses: docker/login-action@v3
      with:
        registry: ${{HARBOR_SERVER}}
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PWD }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{HARBOR_SERVER}}/${{ github.repository }}:latest,${{HARBOR_SERVER}}/${{ github.repository }}:${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64

